@startuml
title
	Database relations Parking Barrier Manager
end title

entity Intercom
{
    * Id : int
    --
	* Name : string
	* MasterCode : string
	* PhoneNumber: string
}

entity OrderedPhoneNumber
{
    * Order: PhoneNumberOrder
	* Number : string
}

entity ApartmentConfiguration
{
	* ApartmentNumber : int
	--
	* MemoryLocation : int
	* DialToOpen : bool
	* Name : string
	AccessCode : string
}

enum PhoneNumberOrder
{
    Primary,
    Secondary,
    Tertiary,
    Quaternary
}

ApartmentConfiguration }|-- OrderedPhoneNumber : one or more
ApartmentConfiguration }|-|{ Intercom : many to many


@enduml