@startuml
title
	Database relations Parking Barrier Manager
end title

entity Intercom
{
    * Id : int
    --
	* Name : string
	* MasterCode : string
	Description : string
}

entity PhoneNumber
{
	* Order: PhoneNumberOrder
	* Number : string
	--
}

entity ApartmentConfiguration
{
	* ApartmentNumber : int
	--
	* MemoryLocation : int
	* DialToOpen : bool
	* Name : string
	AccessCode : string
}

entity Owner
{
	* Id : int
	--
	* Name : string
	Remarks : string
}

entity Transponder
{
	* Number : string
}

enum PhoneNumberOrder
{
    Primary,
    Secondary,
    Tertiary,
    Quaternary
}

Intercom ||-- PhoneNumber : one
ApartmentConfiguration }|-- PhoneNumber : one or more
Owner }|-- Transponder : one or more

@enduml