@startuml

title Shows dependencies between layers according to [[https://www.c-sharpcorner.com/article/what-is-clean-architecture/ Clean Architecture]]

[UserInterface] as UI
[Application] as Application
[Domain] as Domain
[Infrastructure] as Infrastructure

UI --> Application
Application --> Domain
Application --> Infrastructure
Infrastructure --> Domain

@enduml