@startuml

title The UI forms the Compositon Root to wire\n everything up using dependency injection

[UI] as UI
[Application] as Application
[Domain] as Domain
[Infrastructure] as Infrastructure

UI ..> Application
UI ..> Infrastructure

Application --> Domain
Infrastructure --> Domain
Infrastructure --> Application

Domain -[hidden]down- Infrastructure

@enduml