// <auto-generated />
using System;
using Arentheym.ParkingBarrier.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arentheym.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230807142502_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ApartmentConfigurationIntercom", b =>
                {
                    b.Property<string>("ApartmentConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntercomsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ApartmentConfigurationId", "IntercomsId");

                    b.HasIndex("IntercomsId");

                    b.ToTable("ApartmentConfigurationIntercoms", (string)null);
                });

            modelBuilder.Entity("Arentheym.ParkingBarrier.Domain.ApartmentConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AccessCode");

                    b.Property<bool>("DialToOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DialToOpen");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("MemoryLocation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MemoryLocation");

                    b.HasKey("Id");

                    b.ToTable("ApartmentConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "51",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "051",
                            MemoryLocation = (short)51
                        },
                        new
                        {
                            Id = "53",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "053",
                            MemoryLocation = (short)53
                        },
                        new
                        {
                            Id = "55",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "055",
                            MemoryLocation = (short)55
                        },
                        new
                        {
                            Id = "57",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "057",
                            MemoryLocation = (short)57
                        },
                        new
                        {
                            Id = "59",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "059",
                            MemoryLocation = (short)59
                        },
                        new
                        {
                            Id = "61",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "061",
                            MemoryLocation = (short)61
                        },
                        new
                        {
                            Id = "63",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "063",
                            MemoryLocation = (short)63
                        },
                        new
                        {
                            Id = "65",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "065",
                            MemoryLocation = (short)65
                        },
                        new
                        {
                            Id = "67",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "067",
                            MemoryLocation = (short)67
                        },
                        new
                        {
                            Id = "69",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "069",
                            MemoryLocation = (short)69
                        },
                        new
                        {
                            Id = "71",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "071",
                            MemoryLocation = (short)71
                        },
                        new
                        {
                            Id = "73",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "073",
                            MemoryLocation = (short)73
                        },
                        new
                        {
                            Id = "75",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "075",
                            MemoryLocation = (short)75
                        },
                        new
                        {
                            Id = "77",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "077",
                            MemoryLocation = (short)77
                        },
                        new
                        {
                            Id = "79",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "079",
                            MemoryLocation = (short)79
                        },
                        new
                        {
                            Id = "81",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "081",
                            MemoryLocation = (short)81
                        },
                        new
                        {
                            Id = "83",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "083",
                            MemoryLocation = (short)83
                        },
                        new
                        {
                            Id = "85",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "085",
                            MemoryLocation = (short)85
                        },
                        new
                        {
                            Id = "87",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "087",
                            MemoryLocation = (short)87
                        },
                        new
                        {
                            Id = "89",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "089",
                            MemoryLocation = (short)89
                        },
                        new
                        {
                            Id = "91",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "091",
                            MemoryLocation = (short)91
                        },
                        new
                        {
                            Id = "93",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "093",
                            MemoryLocation = (short)93
                        },
                        new
                        {
                            Id = "95",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "095",
                            MemoryLocation = (short)95
                        },
                        new
                        {
                            Id = "97",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "097",
                            MemoryLocation = (short)97
                        },
                        new
                        {
                            Id = "99",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "099",
                            MemoryLocation = (short)99
                        },
                        new
                        {
                            Id = "101",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "101",
                            MemoryLocation = (short)101
                        },
                        new
                        {
                            Id = "103",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "103",
                            MemoryLocation = (short)103
                        },
                        new
                        {
                            Id = "105",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "105",
                            MemoryLocation = (short)105
                        },
                        new
                        {
                            Id = "107",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "107",
                            MemoryLocation = (short)107
                        },
                        new
                        {
                            Id = "109",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "109",
                            MemoryLocation = (short)109
                        },
                        new
                        {
                            Id = "111",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "111",
                            MemoryLocation = (short)111
                        },
                        new
                        {
                            Id = "113",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "113",
                            MemoryLocation = (short)113
                        },
                        new
                        {
                            Id = "115",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "115",
                            MemoryLocation = (short)115
                        },
                        new
                        {
                            Id = "117",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "117",
                            MemoryLocation = (short)117
                        },
                        new
                        {
                            Id = "119",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "119",
                            MemoryLocation = (short)119
                        },
                        new
                        {
                            Id = "121",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "121",
                            MemoryLocation = (short)121
                        },
                        new
                        {
                            Id = "123",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "123",
                            MemoryLocation = (short)123
                        },
                        new
                        {
                            Id = "125",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "125",
                            MemoryLocation = (short)125
                        },
                        new
                        {
                            Id = "127",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "127",
                            MemoryLocation = (short)127
                        },
                        new
                        {
                            Id = "129",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "129",
                            MemoryLocation = (short)129
                        },
                        new
                        {
                            Id = "131",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "131",
                            MemoryLocation = (short)131
                        },
                        new
                        {
                            Id = "133",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "133",
                            MemoryLocation = (short)133
                        },
                        new
                        {
                            Id = "135",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "135",
                            MemoryLocation = (short)135
                        },
                        new
                        {
                            Id = "137",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "137",
                            MemoryLocation = (short)137
                        },
                        new
                        {
                            Id = "139",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "139",
                            MemoryLocation = (short)139
                        },
                        new
                        {
                            Id = "141",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "141",
                            MemoryLocation = (short)141
                        },
                        new
                        {
                            Id = "143",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "143",
                            MemoryLocation = (short)143
                        },
                        new
                        {
                            Id = "145",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "145",
                            MemoryLocation = (short)145
                        },
                        new
                        {
                            Id = "147",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "147",
                            MemoryLocation = (short)147
                        },
                        new
                        {
                            Id = "149",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "149",
                            MemoryLocation = (short)149
                        },
                        new
                        {
                            Id = "151",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "151",
                            MemoryLocation = (short)151
                        },
                        new
                        {
                            Id = "153",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "153",
                            MemoryLocation = (short)153
                        },
                        new
                        {
                            Id = "155",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "155",
                            MemoryLocation = (short)155
                        },
                        new
                        {
                            Id = "157",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "157",
                            MemoryLocation = (short)157
                        },
                        new
                        {
                            Id = "159",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "159",
                            MemoryLocation = (short)159
                        },
                        new
                        {
                            Id = "161",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "161",
                            MemoryLocation = (short)161
                        },
                        new
                        {
                            Id = "163",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "163",
                            MemoryLocation = (short)163
                        },
                        new
                        {
                            Id = "165",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "165",
                            MemoryLocation = (short)165
                        },
                        new
                        {
                            Id = "167",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "167",
                            MemoryLocation = (short)167
                        },
                        new
                        {
                            Id = "169",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "169",
                            MemoryLocation = (short)169
                        },
                        new
                        {
                            Id = "171",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "171",
                            MemoryLocation = (short)171
                        },
                        new
                        {
                            Id = "173",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "173",
                            MemoryLocation = (short)173
                        },
                        new
                        {
                            Id = "175",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "175",
                            MemoryLocation = (short)175
                        },
                        new
                        {
                            Id = "177",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "177",
                            MemoryLocation = (short)177
                        },
                        new
                        {
                            Id = "179",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "179",
                            MemoryLocation = (short)179
                        },
                        new
                        {
                            Id = "181",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "181",
                            MemoryLocation = (short)181
                        },
                        new
                        {
                            Id = "183",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "183",
                            MemoryLocation = (short)183
                        },
                        new
                        {
                            Id = "185",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "185",
                            MemoryLocation = (short)185
                        },
                        new
                        {
                            Id = "187",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "187",
                            MemoryLocation = (short)187
                        },
                        new
                        {
                            Id = "189",
                            AccessCode = "",
                            DialToOpen = true,
                            DisplayName = "189",
                            MemoryLocation = (short)189
                        });
                });

            modelBuilder.Entity("Arentheym.ParkingBarrier.Domain.Intercom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("MasterCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("MasterCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Intercoms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d671f75-9f3d-4f3c-8eb3-7d5200579ef8"),
                            MasterCode = "8601",
                            Name = "Slagboom voor",
                            PhoneNumber = "0657093298"
                        },
                        new
                        {
                            Id = new Guid("0969697d-3314-4f9e-ac6f-007ccfed6e9e"),
                            MasterCode = "8601",
                            Name = "Slagboom achter",
                            PhoneNumber = "0657181402"
                        });
                });

            modelBuilder.Entity("ApartmentConfigurationIntercom", b =>
                {
                    b.HasOne("Arentheym.ParkingBarrier.Domain.ApartmentConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ApartmentConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arentheym.ParkingBarrier.Domain.Intercom", null)
                        .WithMany()
                        .HasForeignKey("IntercomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arentheym.ParkingBarrier.Domain.ApartmentConfiguration", b =>
                {
                    b.OwnsMany("Arentheym.ParkingBarrier.Domain.DivertPhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<string>("ApartmentConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Order");

                            b1.Property<string>("Number")
                                .HasColumnType("TEXT")
                                .HasColumnName("Number");

                            b1.HasKey("ApartmentConfigurationId", "Order", "Number");

                            b1.ToTable("ApartmentConfigurationPhoneNumbers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApartmentConfigurationId");
                        });

                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
